services:
  # Frontend (React App)
  - type: web
    name: pragmadao-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_BACKEND_URL
        sync: false
    

  # Backend (Node.js API)
  - type: web
    name: pragmadao-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm ci --include=dev && npx prisma generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    
databases:
  - name: pragmadao-db
    databaseName: pragmadao
    user: pragmadao